<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
امید به زندگی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
به تمرین «امید به زندگی» خوش آمدید :)
    <br>
    هدف این تمرین این است که با مورد بررسی قرار دادن شاخص‌های بهداشتی، مالی و کشوری، امید به زندگی کشورها را پیش‌بینی کنیم.
    <br>
    امید به زندگی یا متوسط طول عمر (به انگلیسی: Life Expectancy) یک شاخص آماری است که نشان می‌دهد اعضای یک جامعه به‌طور میانگین چقدر عمر می‌کنند، یا به عبارت دیگر، انتظار می‌رود چقدر عمر کنند. اطلاعات بیشتر درباره‌ی امید به زندگی را می‌توانید در 
<a href="https://fa.wikipedia.org/wiki/%D8%A7%D9%85%DB%8C%D8%AF_%D8%A8%D9%87_%D8%B2%D9%86%D8%AF%DA%AF%DB%8C">ویکی‌پدیا</a> 
    مطالعه کنید.
    
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مجموعه‌داده‌ی آموزشی مسئله دارای ۲۸۴۸ سطر و ۱۸ ستون است.
    ۱۷ ستون مربوط به متغیرهای مستقل و ستون آخر هم نشانگر متغیر وابسته مسئله است.
    <br>
    در جدول زیر توضیح هر ستون را مشاهده می‌کنید. هر سطر مربوط به اطلاعات یک کشور است که در یک سال مشخص رکورد شده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Country</code>|کشور مورد مطالعه|
|<code>Year</code>|سال|
|<code>Status</code>|وضعیت توسعه‌یافتگی کشور|
|<code>Population</code>|جمعیت کشور|
|<code>Hepatitis B</code>|درصد افراد نهایتاً یک ساله‌ای که در برابر هپاتیت ب ایمن شده‌اند|
|<code>Measles</code>|تعداد موارد مبتلا به سرخک گزارش شده در هر ۱۰۰۰ نفر|
|<code>Polio</code>|درصد افراد نهایتاً یک ساله‌ای که در برابر فلج اطفال ایمن شده‌اند|
|<code>Diphtheria</code>|درصد افراد نهایتاً یک ساله‌ای که در برابر دیفتری ایمن شده‌اند|
|<code>HIV/AIDS</code>|تعداد فوتی‌های ناشی از ایدز افراد نهایتاً ۴ ساله‌ای که زنده به دنیا آمده‌اند در هر ۱۰۰۰ نفر|
|<code>infant deaths</code>|تعداد فوتی‌های نوزادان در هر ۱۰۰۰ نفر|
|<code>under-five deaths</code>|تعداد فوتی‌های افراد نهایتاً ۵ ساله در هر ۱۰۰۰ نفر|
|<code>Total expenditure</code>|نسبت هزینه‌های درمانی-بهداشتی دولت به کل هزینه‌های دولت بر حسب درصد|
|<code>GDP</code>|تولید ناخالص ملی بر حسب دلار امریکا|
|<code>BMI</code>|میانگین شاخص توده بدنی کل جمعیت کشور|
|<code>thinness 1-19 years</code>|میزان شیوع لاغری میان افراد نهایتاً ۱۹ ساله بر حسب درصد|
|<code>Alcohol</code>|میزان لیتر مصرف الکل بین افراد بیشتر از ۱۵ سال|
|<code>Schooling</code>|تعداد سالی که افراد تحصیل می‌کنند|
|<code>Life expectancy</code>|امید به زندگی یا متوسط طول عمر|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
     مجموعه‌ی آزمون (تست) مانند مجموعه‌ی آموزش است با این تفاوت که ستون <code>Life expectancy</code> را ندارد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید مقدار متغیر هدف آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزش را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [2]:
train_data = pd.read_csv('../data/train.csv')
train_data

,Country,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling,Life expectancy
0,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,83,8.16,584.259210,19.1,17.2,0.01,10.1,65.0
1,Afghanistan,2014,Developing,327582.0,62.0,492,58.0,62.0,0.1,64,86,8.18,612.696514,18.6,17.5,0.01,10.0,59.9
2,Afghanistan,2013,Developing,31731688.0,64.0,430,62.0,64.0,0.1,66,89,8.13,631.744976,18.1,17.7,0.01,9.9,59.9
3,Afghanistan,2012,Developing,3696958.0,67.0,2787,67.0,67.0,0.1,69,93,8.52,669.959000,17.6,17.9,0.01,9.8,59.5
4,Afghanistan,2011,Developing,2978599.0,68.0,3013,68.0,68.0,0.1,71,97,7.87,63.537231,17.2,18.2,0.01,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843,Zimbabwe,2004,Developing,12777511.0,68.0,31,67.0,65.0,33.6,27,42,7.13,454.366654,27.1,9.4,4.36,9.2,44.3
2844,Zimbabwe,2003,Developing,12633897.0,7.0,998,7.0,68.0,36.7,26,41,6.52,453.351155,26.7,9.8,4.06,9.5,44.5
2845,Zimbabwe,2002,Developing,125525.0,73.0,304,73.0,71.0,39.8,25,40,6.53,57.348340,26.3,1.2,4.43,10.0,44.8
2846,Zimbabwe,2001,Developing,12366165.0,76.0,529,76.0,75.0,42.1,25,39,6.16,548.587312,25.9,1.6,1.72,9.8,45.3
2847,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,39,7.10,547.358878,25.5,11.0,1.68,9.8,46.0

In [3]:
test_data = pd.read_csv('../data/test.csv')
test_data

,Country,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling
0,Burundi,2015,Developing,119927.0,94.0,9,94.0,94.0,0.7,21,31,NaN,33.681223,18.7,7.3,NaN,10.6
1,Burundi,2014,Developing,989179.0,95.0,0,95.0,95.0,0.7,22,32,7.54,312.748979,18.2,7.4,0.01,10.6
2,Burundi,2013,Developing,96186.0,96.0,0,96.0,96.0,1.0,22,32,8.30,282.755525,17.6,7.4,0.01,10.5
3,Burundi,2012,Developing,931971.0,96.0,49,96.0,96.0,1.2,22,33,8.21,265.285651,17.1,7.5,0.01,10.3
4,Burundi,2011,Developing,94358.0,96.0,129,95.0,96.0,1.5,22,33,8.58,26.479973,16.6,7.6,4.16,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Papua New Guinea,2004,Developing,6161517.0,6.0,1385,59.0,62.0,1.5,11,15,8.39,637.361621,4.4,1.5,0.58,7.6
76,Papua New Guinea,2003,Developing,61724.0,67.0,3863,62.0,68.0,1.4,11,14,6.79,588.358260,39.6,1.5,0.59,7.2
77,Papua New Guinea,2002,Developing,5862316.0,6.0,17620,54.0,61.0,1.4,11,14,7.69,511.665773,38.9,1.5,0.61,6.9
78,Papua New Guinea,2001,Developing,5716152.0,59.0,4023,52.0,55.0,1.3,11,14,6.68,539.415280,38.2,1.5,0.68,6.6
79,Papua New Guinea,2000,Developing,5572222.0,57.0,7135,51.0,59.0,1.1,11,14,3.98,631.946853,37.5,1.6,0.73,6.2

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [6]:
train_data.isna().sum()

Country                   0
Year                      0
Status                    0
Population              644
Hepatitis B             542
Measles                   0
Polio                    19
Diphtheria               19
HIV/AIDS                  0
infant deaths             0
under-five deaths         0
Total expenditure       221
GDP                     442
BMI                      32
thinness  1-19 years     32
Alcohol                 188
Schooling               160
Life expectancy           0
dtype: int64

In [5]:
mapping = {'Developed' : 1, 'Developing' : 0}
train_data['Status'] = train_data['Status'].map(mapping)
test_data['Status'] = test_data['Status'].map(mapping)

In [8]:
# mean_val_Status = train_data['Status'].groupby(train_data['Country']).transform('mean')
mean_val_population = train_data['Population'].groupby(train_data['Country']).transform('mean')
mean_val_HepatitisB = train_data['Hepatitis B'].groupby(train_data['Country']).transform('mean')
mean_val_Polio = train_data['Polio'].groupby(train_data['Country']).transform('mean')
mean_val_Diphtheria = train_data['Diphtheria'].groupby(train_data['Country']).transform('mean')
mean_val_Totalexpenditure = train_data['Total expenditure'].groupby(train_data['Country']).transform('mean')
mean_val_GDP = train_data['GDP'].groupby(train_data['Country']).transform('mean')
mean_val_BMI = train_data['BMI'].groupby(train_data['Country']).transform('mean')
mean_val_thinnessyears = train_data['thinness  1-19 years'].groupby(train_data['Country']).transform('mean')
mean_val_Alcohol = train_data['Alcohol'].groupby(train_data['Country']).transform('mean')
mean_val_Schooling = train_data['Schooling'].groupby(train_data['Country']).transform('mean')
# train_data['Status'].fillna(mean_val_Status, inplace=True)
train_data['Population'].fillna(mean_val_population, inplace=True)
train_data['Hepatitis B'].fillna(mean_val_HepatitisB, inplace=True)
train_data['Polio'].fillna(mean_val_Polio, inplace=True)
train_data['Diphtheria'].fillna(mean_val_Diphtheria, inplace=True)
train_data['Total expenditure'].fillna(mean_val_Totalexpenditure, inplace=True)
train_data['GDP'].fillna(mean_val_GDP, inplace=True)
train_data['BMI'].fillna(mean_val_BMI, inplace=True)
train_data['thinness  1-19 years'].fillna(mean_val_thinnessyears, inplace=True)
train_data['Alcohol'].fillna(mean_val_Alcohol, inplace=True)
train_data['Schooling'].fillna(mean_val_Schooling, inplace=True)

In [9]:
train_data.isna().sum()

Country                   0
Year                      0
Status                    0
Population              640
Hepatitis B             144
Measles                   0
Polio                     0
Diphtheria                0
HIV/AIDS                  0
infant deaths             0
under-five deaths         0
Total expenditure        32
GDP                     400
BMI                      32
thinness  1-19 years     32
Alcohol                  16
Schooling               160
Life expectancy           0
dtype: int64

In [10]:
train_data.drop('Country', axis=1, inplace=True)
test_data.drop('Country', axis=1, inplace=True)

In [11]:
# median_val_Status = train_data['Status'].median()
median_val_population = train_data['Population'].median()
median_val_HepatitisB = train_data['Hepatitis B'].median()
median_val_Totalexpenditure = train_data['Total expenditure'].median()
median_val_GDP = train_data['GDP'].median()
median_val_BMI = train_data['BMI'].median()
median_val_thinnessyears = train_data['thinness  1-19 years'].median()
median_val_Alcohol = train_data['Alcohol'].median()
median_val_Schooling = train_data['Schooling'].median()
train_data['Population'].fillna(median_val_population, inplace=True)
train_data['Hepatitis B'].fillna(median_val_HepatitisB, inplace=True)
train_data['Total expenditure'].fillna(median_val_Totalexpenditure, inplace=True)
train_data['GDP'].fillna(median_val_GDP, inplace=True)
train_data['BMI'].fillna(median_val_BMI, inplace=True)
train_data['thinness  1-19 years'].fillna(median_val_thinnessyears, inplace=True)
train_data['Alcohol'].fillna(median_val_Alcohol, inplace=True)
train_data['Schooling'].fillna(median_val_Schooling, inplace=True)

In [12]:
test_data.isna().sum()

Year                     0
Status                   0
Population               0
Hepatitis B             11
Measles                  0
Polio                    0
Diphtheria               0
HIV/AIDS                 0
infant deaths            0
under-five deaths        0
Total expenditure        5
GDP                      1
BMI                      0
thinness  1-19 years     0
Alcohol                  5
Schooling                0
dtype: int64

In [13]:
test_data['Hepatitis B'].fillna(mean_val_HepatitisB, inplace=True)
test_data['Total expenditure'].fillna(mean_val_Totalexpenditure, inplace=True)
test_data['GDP'].fillna(mean_val_GDP, inplace=True)
test_data['Alcohol'].fillna(mean_val_Alcohol, inplace=True)

In [14]:
train_data.isna().sum()

Year                    0
Status                  0
Population              0
Hepatitis B             0
Measles                 0
Polio                   0
Diphtheria              0
HIV/AIDS                0
infant deaths           0
under-five deaths       0
Total expenditure       0
GDP                     0
BMI                     0
thinness  1-19 years    0
Alcohol                 0
Schooling               0
Life expectancy         0
dtype: int64

In [15]:
test_data.isna().sum()

Year                    0
Status                  0
Population              0
Hepatitis B             0
Measles                 0
Polio                   0
Diphtheria              0
HIV/AIDS                0
infant deaths           0
under-five deaths       0
Total expenditure       0
GDP                     0
BMI                     0
thinness  1-19 years    0
Alcohol                 0
Schooling               0
dtype: int64

In [16]:
train_data

,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling,Life expectancy
0,2015,0,33736494.0,65.0,1154,6.0,65.0,0.1,62,83,8.16,584.259210,19.1,17.2,0.01,10.1,65.0
1,2014,0,327582.0,62.0,492,58.0,62.0,0.1,64,86,8.18,612.696514,18.6,17.5,0.01,10.0,59.9
2,2013,0,31731688.0,64.0,430,62.0,64.0,0.1,66,89,8.13,631.744976,18.1,17.7,0.01,9.9,59.9
3,2012,0,3696958.0,67.0,2787,67.0,67.0,0.1,69,93,8.52,669.959000,17.6,17.9,0.01,9.8,59.5
4,2011,0,2978599.0,68.0,3013,68.0,68.0,0.1,71,97,7.87,63.537231,17.2,18.2,0.01,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843,2004,0,12777511.0,68.0,31,67.0,65.0,33.6,27,42,7.13,454.366654,27.1,9.4,4.36,9.2,44.3
2844,2003,0,12633897.0,7.0,998,7.0,68.0,36.7,26,41,6.52,453.351155,26.7,9.8,4.06,9.5,44.5
2845,2002,0,125525.0,73.0,304,73.0,71.0,39.8,25,40,6.53,57.348340,26.3,1.2,4.43,10.0,44.8
2846,2001,0,12366165.0,76.0,529,76.0,75.0,42.1,25,39,6.16,548.587312,25.9,1.6,1.72,9.8,45.3
2847,2000,0,12222251.0,79.0,1483,78.0,78.0,43.5,24,39,7.10,547.358878,25.5,11.0,1.68,9.8,46.0

In [17]:
test_data

,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling
0,2015,0,119927.0,94.0,9,94.0,94.0,0.7,21,31,8.2525,33.681223,18.7,7.3,0.014375,10.6
1,2014,0,989179.0,95.0,0,95.0,95.0,0.7,22,32,7.5400,312.748979,18.2,7.4,0.010000,10.6
2,2013,0,96186.0,96.0,0,96.0,96.0,1.0,22,32,8.3000,282.755525,17.6,7.4,0.010000,10.5
3,2012,0,931971.0,96.0,49,96.0,96.0,1.2,22,33,8.2100,265.285651,17.1,7.5,0.010000,10.3
4,2011,0,94358.0,96.0,129,95.0,96.0,1.5,22,33,8.5800,26.479973,16.6,7.6,4.160000,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2004,0,6161517.0,6.0,1385,59.0,62.0,1.5,11,15,8.3900,637.361621,4.4,1.5,0.580000,7.6
76,2003,0,61724.0,67.0,3863,62.0,68.0,1.4,11,14,6.7900,588.358260,39.6,1.5,0.590000,7.2
77,2002,0,5862316.0,6.0,17620,54.0,61.0,1.4,11,14,7.6900,511.665773,38.9,1.5,0.610000,6.9
78,2001,0,5716152.0,59.0,4023,52.0,55.0,1.3,11,14,6.6800,539.415280,38.2,1.5,0.680000,6.6
79,2000,0,5572222.0,57.0,7135,51.0,59.0,1.1,11,14,3.9800,631.946853,37.5,1.6,0.730000,6.2

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای الگوریتم رگرسیون چند‌جمله‌ای پکیج یکتایی در کتابخانه‌ی <code>scikit-learn</code> وجود ندارد. بنابراین برای استفاده از این الگوریتم، می‌بایست ابتدا ویژگی‌های دیتافریم را با استفاده از کلاس <code>PolynomialFeatures</code> که در پکیج <code>preprocessing</code> قرار دارد، به ویژگی‌های چندجمله‌ای تبدیل کنید. سپس از آن ویژگی‌های تغییریافته (<code>transformed</code>) برای آموزش یک رگرسیون خطی معمولی استفاده کنید.
    <br>
    برخی از آرگومان‌های مهم این کلاس در جدول زیر آمده است، اما برای مطالعه کامل‌تر مستندات می‌توانید به <a href="https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html">این لینک</a> مراجعه فرمایید.

</font>
</div>
    
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<br>

|آرگومان|نوع|توضیحات|
|:------:|:--------:|:---:|
|<code>degree</code>|<code>int</code> یا <code>tuple</code>|درجه چند جمله‌ای را نشان می‌دهد. به‌صورت پیش‌فرض عدد <code>2</code> است.<br> اگر به شکل <code>tuple</code> باشد، به شکل <code dir=ltr>(min_degree, max_degree)</code> تفسیر می‌شود.|
|<code>include_bias</code>|<code>bool</code>|آیا شامل بایاس باشد یا خیر. <br> در صورت <code>True</code> بودن، عدد <code>1</code> هم به چندجمله‌ای افزوده می‌شود. <br> (به این معنی که چندجمله‌ای‌های تولید‌شده حداقل از درجه‌ی <code>min_degree</code> و حداکثر از مرتبه‌ی <code>max_degree</code> خواهند بود.)|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    کلاس <code>PolynomialFeatures</code> دارای سه متد به شرح زیر است: 
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|اسم متد|توضیحات|
|:------:|:---:|
|<code>fit</code>|تعداد جملات چندجمله‌ای خروجی را حساب می‌کند|
|<code>transform</code>|داده‌ی ورودی را به جملات چند‌جمله‌ای تبدیل می‌کند|
|<code>fit_transform</code>|ابتدا تابع <code>fit</code> و سپس تابع <code>transform</code> را اجرا می‌کند|

</font>
</div>
</center>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سلول پایین با استفاده از کتابخانه‌ی <code>scikit-learn</code> مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    <br>
    برای ساختن ویژگی‌های چندجمله‌ای، شیء <code>poly_transformer</code> را مقداردهی کنید. بعداً در سلول جواب‌ساز این شیء ذخیره شده و در زمان داوری، مورد ارزیابی واقع خواهد شد.
    <br>
     سپس با ویژگی‌های چندجمله‌ای خروجی <code>poly_transformer</code> مدل رگرسیون خطی را آموزش دهید و آن را در شیء <code>model</code> ذخیره کنید. متغیر <code>model</code> در فرآیند داوری مورد ارزیابی واقع خواهد شد. بنابراین اطمینان حاصل کنید که از جنس <code>LinearRegression</code> باشد؛ در غیر این صورت نمره‌ای دریافت نخواهید کرد!
</font>
</p>

In [18]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

y = train_data['Life expectancy']
x = train_data.drop('Life expectancy', axis=1)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

std_scaler = StandardScaler()
X_train = std_scaler.fit_transform(X_train)
X_test = std_scaler.transform(X_test)
poly_transformer = PolynomialFeatures(degree=2, include_bias=True)
x_train_trans = poly_transformer.fit_transform(X_train)
x_test_trans = poly_transformer.transform(X_test)

In [19]:
from sklearn.linear_model import LinearRegression

model = LinearRegression() 
model.fit(x_train_trans, y_train)
y_pred = model.predict(x_test_trans)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>r2_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [20]:
# evaluate your model
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.831011932114214

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>50</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در مجموعه‌ی آزمون استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Life expectancy</code>|امید به زندگی پیش‌بینی‌شده|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    توجه داشته باشید که نام دیتافریم باید <code>submission</code> باشد؛ در غیر این‌صورت، سامانه‌ی داوری قادر به ارزیابی خروجی شما نخواهد بود.
    این دیتافریم تنها شامل ۱ ستون با اسم <code>Life expectancy</code> است و ۸۰ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <code>test</code>، باید یک مقدار پیش‌بینی‌شده داشته باشید.
    به‌عنوان مثال جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، اعداد ستون <code>Life expectancy</code> ممکن است متفاوت باشد.
</font>
</p>

<center>
<div style="direction: ltr;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||<code>Life expectancy</code>|
|:----:|:-----:|
|0|70.1|
|1|65.2|
|2|50.0|
|3|81.72|
|4|75.25|

</font>
</div>
</center>

In [29]:
# استفاده از مدل رگرسیون چندجمله‌ای
x_test = test_data  # داده‌های تست
x_test = std_scaler.transform(x_test)  # استانداردسازی داده‌های تست

x_test_trans = poly_transformer.transform(x_test)  # تبدیل داده‌های تست به فضای چندجمله‌ای

y_pred_test = model.predict(x_test_trans)  # پیش‌بینی برای داده‌های تست

# ساخت دیتافریم submission
submission = pd.DataFrame({'Life expectancy': y_pred_test})

# ذخیره دیتافریم submission در فایل CSV
# submission.to_csv('submission.csv', index=False)
# submission = pd.DataFrame()
# # submission['Life expectancy'] = model.predict(test_data)

# x_test_trans = poly_transformer.transform(test_data)
# submission['Life expectancy'] = model.predict(x_test_trans)
submission

    Life expectancy
0         65.224754
1         65.513517
2         64.978974
3         64.228310
4         63.469202
..              ...
75        55.900902
76        62.823956
77        59.574790
78        61.744029
79        62.795042

[80 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [31]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)


joblib.dump(poly_transformer, 'poly_transformer')
joblib.dump(model, 'model')
submission.to_csv('submission.csv', index=False)

file_names = ['poly_transformer', 'model', 'submission.csv', 'life_expectancy.ipynb']
compress(file_names)

File Paths:
['poly_transformer', 'model', 'submission.csv', 'life_expectancy.ipynb']

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
راهنمایی
</font>
</h4>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ۱. در مراحل پیش‌پردازش از تغییر مقیاس ویژگی استفاده کنید.
    <br>
    ۲. مقادیر گم‌شده‌ی ویژگی‌ها را بررسی و مدیریت کنید.
</font>
</p>